-- Expand global exercise catalog (idempotent — skips names that already exist).

CREATE UNIQUE INDEX IF NOT EXISTS exercises_name_lower_unique
  ON public.exercises (lower(trim(name)));

INSERT INTO public.exercises (name, target_muscle, description)
SELECT v.name, v.target_muscle, v.description
FROM (
  VALUES
    ('Ab Wheel Rollout', 'Core', 'Anti-extension core exercise using an ab wheel.'),
    ('Arnold Press', 'Shoulders', 'Rotating dumbbell overhead press.'),
    ('Back Squat', 'Quads', 'Barbell back squat.'),
    ('Band Pull-Apart', 'Rear Delts', 'Rear delt and upper back activation with a band.'),
    ('Barbell Shrug', 'Grip / Traps', 'Vertical trap shrug with a barbell.'),
    ('Belt Squat', 'Quads', 'Squat pattern without axial spinal loading.'),
    ('Bicycle Crunch', 'Core', 'Alternating elbow-to-knee crunch.'),
    ('Box Squat', 'Quads', 'Squat to a box or bench for consistent depth.'),
    ('Cable Crossover', 'Chest', 'High-to-low or low-to-high cable fly variation.'),
    ('Cable Curl', 'Biceps', 'Constant-tension biceps curl with cable.'),
    ('Cable Hip Abduction', 'Glutes', 'Hip abduction using a low cable.'),
    ('Cable Kickback', 'Glutes', 'Glute kickback with ankle strap.'),
    ('Cable Lateral Raise', 'Shoulders', 'Lateral raise using a low cable.'),
    ('Cable Overhead Extension', 'Triceps', 'Overhead triceps extension with rope or bar.'),
    ('Cable Pull-Through', 'Hamstrings', 'Hip hinge pattern with cable between the legs.'),
    ('Cable Woodchop', 'Core', 'Rotational core exercise with cable stack.'),
    ('Chest-Supported Row', 'Back', 'Incline bench supported dumbbell or machine row.'),
    ('Close-Grip Bench Press', 'Triceps', 'Narrow-grip bench press emphasizing triceps.'),
    ('Concentration Curl', 'Biceps', 'Seated single-arm curl with elbow braced.'),
    ('Conventional Deadlift', 'Legs', 'Standard barbell deadlift from the floor.'),
    ('Decline Bench Press', 'Chest', 'Decline barbell or dumbbell press.'),
    ('Dead Bug', 'Core', 'Supine anti-extension core drill.'),
    ('Dips', 'Triceps', 'Parallel bar or bench dips for chest and triceps.'),
    ('Donkey Calf Raise', 'Calves', 'Bent-over calf raise with partner or machine.'),
    ('Dumbbell Bench Press', 'Chest', 'Flat dumbbell bench press.'),
    ('Dumbbell Fly', 'Chest', 'Flat or incline dumbbell fly.'),
    ('Dumbbell Kickback', 'Triceps', 'Single-arm triceps kickback.'),
    ('Dumbbell Row', 'Back', 'Single-arm or bilateral dumbbell row.'),
    ('Dumbbell Shrug', 'Grip / Traps', 'Trap shrug with dumbbells.'),
    ('Dumbbell Shoulder Press', 'Shoulders', 'Seated or standing dumbbell overhead press.'),
    ('EZ-Bar Curl', 'Biceps', 'Curl with EZ curl bar.'),
    ('Floor Press', 'Chest', 'Limited-range bench press from the floor.'),
    ('Front Raise', 'Shoulders', 'Anterior delt raise with dumbbells or plate.'),
    ('Front Squat', 'Quads', 'Barbell front rack squat.'),
    ('Frog Pump', 'Glutes', 'Feet together glute bridge pump.'),
    ('Glute Bridge', 'Glutes', 'Bodyweight or loaded hip bridge.'),
    ('Glute Ham Raise', 'Hamstrings', 'GHD or glute-ham developer raise.'),
    ('Goblet Squat', 'Quads', 'Front-loaded squat holding a dumbbell or kettlebell.'),
    ('Good Morning', 'Hamstrings', 'Barbell hip hinge with bar on the back.'),
    ('Hack Squat', 'Quads', 'Machine or barbell hack squat.'),
    ('Hanging Leg Raise', 'Core', 'Hanging knee or leg raise.'),
    ('Incline Barbell Bench Press', 'Chest', 'Incline barbell bench press.'),
    ('Incline Dumbbell Curl', 'Biceps', 'Incline bench dumbbell curl.'),
    ('Inverted Row', 'Back', 'Bodyweight horizontal row under a bar.'),
    ('JM Press', 'Triceps', 'Hybrid close-grip press and skull crusher.'),
    ('Leg Press Calf Raise', 'Calves', 'Calf raise on leg press foot plate.'),
    ('Low Cable Fly', 'Chest', 'Low pulley cable fly.'),
    ('Low Row', 'Back', 'Low cable or machine row.'),
    ('Machine Chest Press', 'Chest', 'Seated machine horizontal press.'),
    ('Machine Fly', 'Chest', 'Pec deck or machine fly.'),
    ('Machine Row', 'Back', 'Seated machine row.'),
    ('Machine Shoulder Press', 'Shoulders', 'Seated machine overhead press.'),
    ('Meadows Row', 'Back', 'Landmine single-arm row variation.'),
    ('Neutral-Grip Pull-Up', 'Back', 'Pull-up with parallel handles.'),
    ('Nordic Curl', 'Hamstrings', 'Eccentric hamstring curl from knees.'),
    ('One-Arm Cable Row', 'Back', 'Single-arm seated cable row.'),
    ('Overhead Tricep Extension', 'Triceps', 'Two-hand dumbbell overhead extension.'),
    ('Overhead Carry', 'Shoulders', 'Loaded carry with weight locked out overhead.'),
    ('Pallof Press', 'Core', 'Anti-rotation press with cable or band.'),
    ('Pec Deck', 'Chest', 'Machine chest fly.'),
    ('Pendlay Row', 'Back', 'Dead-stop barbell row from the floor.'),
    ('Preacher Curl', 'Biceps', 'Arm-supported curl on preacher bench.'),
    ('Push Press', 'Shoulders', 'Overhead press with leg drive.'),
    ('Push-Up', 'Chest', 'Bodyweight horizontal push.'),
    ('Rack Pull', 'Grip / Traps', 'Partial deadlift from pins or blocks.'),
    ('Rear Delt Fly', 'Rear Delts', 'Reverse fly for rear delts.'),
    ('Reverse Lunge', 'Quads', 'Stepping backward into a lunge.'),
    ('Reverse Pec Deck', 'Rear Delts', 'Machine reverse fly.'),
    ('Romanian Deadlift', 'Hamstrings', 'Hip hinge with slight knee bend.'),
    ('Rope Tricep Pushdown', 'Triceps', 'Triceps pushdown with rope attachment.'),
    ('Russian Twist', 'Core', 'Seated or floor rotational twist.'),
    ('Safety Bar Squat', 'Quads', 'Squat using a safety squat bar.'),
    ('Seated Cable Row', 'Back', 'Horizontal cable row from low pulley.'),
    ('Seated Calf Raise', 'Calves', 'Seated machine or dumbbell calf raise.'),
    ('Seated Dumbbell Press', 'Shoulders', 'Overhead press seated with dumbbells.'),
    ('Side Plank', 'Core', 'Lateral isometric core hold.'),
    ('Single-Leg Calf Raise', 'Calves', 'Unilateral standing calf raise.'),
    ('Single-Leg Hip Thrust', 'Glutes', 'Unilateral hip thrust.'),
    ('Single-Leg Romanian Deadlift', 'Hamstrings', 'Unilateral RDL pattern.'),
    ('Smith Machine Bench Press', 'Chest', 'Bench press on Smith machine.'),
    ('Smith Machine Squat', 'Quads', 'Squat on Smith machine.'),
    ('Spider Curl', 'Biceps', 'Incline bench spider curl.'),
    ('Step-Up', 'Quads', 'Box or bench step-up.'),
    ('Stiff-Leg Deadlift', 'Hamstrings', 'Deadlift with minimal knee bend.'),
    ('Straight-Arm Pulldown', 'Back', 'Lat isolation with straight arms.'),
    ('Sumo Deadlift', 'Legs', 'Wide-stance deadlift.'),
    ('Suitcase Carry', 'Core', 'Unilateral farmer carry for anti-lateral flexion.'),
    ('Trap Bar Deadlift', 'Legs', 'Deadlift using trap bar.'),
    ('Upright Row', 'Shoulders', 'Vertical pull with narrow grip.'),
    ('Wide-Grip Lat Pulldown', 'Back', 'Lat pulldown with wide grip.'),
    ('Wrist Curl', 'Grip / Traps', 'Forearm flexor curl.'),
    ('Zercher Squat', 'Quads', 'Front-loaded squat with bar in elbow crooks.')
) AS v(name, target_muscle, description)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.exercises e
  WHERE lower(trim(e.name)) = lower(trim(v.name))
);
